version: "1"
services:
  node:
    build:
      context: .
      dockerfile: dockerfile
    command: "npm run dev"
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"